spring:
  application:
    name: CatalogService

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/catalog_db}
      uuid-representation: standard

server:
  port: ${PORT:8080}
  
eureka:
  client:
    enabled: false
    
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
    org.mongodb.driver.connection: DEBUG
    org.mongodb.driver.cluster: DEBUG
